//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> phone { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
    }
}
