//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3_delivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_1
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string name1 { get; set; }
        public Nullable<int> int1 { get; set; }
        public Nullable<int> int2 { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
